[versions]
android="7.0.0"
annotation = "1.2.0"
dokka = "1.5.0"
gson = "2.8.7"
kotlin = "1.5.30-RC"
spek = "2.0.15"

[plugins]
android = { id = "com.android.library", version.ref = "android" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
spek-dsl-metadata = { module = "org.spekframework.spek2:spek-dsl-metadata", version.ref = "spek" }
spek-dsl-jvm = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
spek-runner = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }
