[versions]
android = "7.0.3" # Do Not Update this until Kotlin Updated to 1.6.10
android-buildtools = "32.0.0"
dokka = "1.6.10"
kotest = "5.2.3"
serialization = "1.3.1"

[plugins]
android = { id = "com.android.library", version.ref = "android" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotest = { id = "io.kotest.multiplatform", version.ref = "kotest" }

[libraries]
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[bundles]
test-android = [ "kotest-runner" ]

test-common = [ "kotest-assertions", "kotest-engine" ]
