[versions]
android = "7.0.2"
android-buildtools = "31.0.0"
dokka = "1.5.30"
junit = "5.7.2"
kotlin = "1.5.31"
kotlin-api = "1.4"
serialization = "1.3.0"
spek = "2.0.17"

[plugins]
android = { id = "com.android.library", version.ref = "android" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
spek-dsl = { module = "org.spekframework.spek2:spek-dsl", version.ref = "spek" }
spek-runtime = { module = "org.spekframework.spek2:spek-runtime", version.ref = "spek" }
spek-junit5runner = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }

[bundles]
test-common = [
    "junit-api",
    "spek-dsl"
]