name: CSharp
on:
  push:
    branches:
      - main
    paths:
      - 'csharp/**'
      - '.github/workflows/csharp*'
  pull_request:
    paths:
      - 'csharp/**'
      - '.github/workflows/csharp*'


jobs:
  tests:
    name: Running CSharp Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2

      - name: Install dependencies
        run: nuget restore
        working-directory: csharp

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: csharp

      - name: Run Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: csharp
