name: CSharp
on:
  push:
    branches:
      - main
    paths:
      - 'csharp/**'
      - '.github/workflows/csharp*'
  pull_request:
    paths:
      - 'csharp/**'
      - '.github/workflows/csharp*'


jobs:
  tests:
    name: Running CSharp Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Install dependencies
        run: nuget restore
        working-directory: csharp

      - name: Run Test
        run: dotnet test --no-restore
        working-directory: csharp
