name: CSharp
on:
  push:
    branches:
      - main
    paths:
      - 'csharp/**'
      - '.github/workflows/csharp*'
  pull_request:
    paths:
      - 'csharp/**'
      - '.github/workflows/csharp*'


jobs:
  tests:
    name: Running CSharp Tests
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Test
        run: |
          dotnet test OpenRTB.Tests.csproj
        working-directory: ./csharp/OpenRTB.Tests
