name: Go
on:
  push:
    branches:
    - master
    - 'go/*'
  pull_request:
    branches:
    - 'go/*'
    
jobs:

  test:
    name: Test Go OpenRTB
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        if [ ! -f "/tmp/GeoLite2-City.mmdb.gz" ]; then
            wget -O /tmp/GeoLite2-City.mmdb.gz https://s3.amazonaws.com/timehop.uploads/oneoffs/GeoLite2-City.mmdb.gz
        fi

    - name: Run Test
      env:
        LOAD_MAXMIND_FROM_FILE: "true"
        MAXMIND_FILE: "/tmp/GeoLite2-City.mmdb.gz"
      run: go test ./... -race -cover -v -short
