name: Kotlin

on:
  pull_request:
    branches:
      - main
    paths:
      - 'kotlin/**'
      - '.github/workflows/kotlin*'

  push:
    tags-ignore:
      - '**'


  release:
    types: [published]

jobs:

  build:
    name: Build, test, and optionally publish Android OpenRTB to Bintray
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }}
      ORG_GRADLE_PROJECT_bintrayUsername: ${{ secrets.BINTRAY_USER }}
      ORG_GRADLE_PROJECT_bintrayPassword: ${{ secrets.BINTRAY_API_KEY }}
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
            ${{ runner.os }}-gradle-

      - name: Fix NDK Bug
        run: echo "ndk.dir=$ANDROID_HOME/ndk-bundle" > local.properties

      - name: Build
        run: ./gradlew build

      - name: Publish
        if: success() && github.event_name == 'release'
        run: ./gradlew publish