name: Kotlin

on:
  pull_request:
    branches:
      - main
    paths:
      - 'kotlin/**'
      - '.github/workflows/kotlin*'

  push:
    tags-ignore:
      - '**'


  release:
    types: [published]

jobs:

  build:
    name: Build, test, and optionally publish Android OpenRTB
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref }}
      ORG_GRADLE_PROJECT_awsAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
      ORG_GRADLE_PROJECT_awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Cache Kotlin packages
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}
            ${{ runner.os }}-konan-

      - name: Fix NDK Bug
        run: echo "ndk.dir=$ANDROID_HOME/ndk-bundle" > local.properties

      - name: Build
        run: ./gradlew build

      - name: Publish
        if: success() && github.event_name == 'release'
        run: ./gradlew publish
