name: Kotlin

on:
  pull_request:
    paths:
      - '.github/workflows/kotlin*'
      - '**/gradle/**'
      - 'kotlin/**'

  push:
    branches:
      - main
    paths:
      - '.github/workflows/kotlin*'
      - '**/gradle/**'
      - 'kotlin/**'

  release:
    types: [published]

jobs:

  build:
    name: Build Kotlin Multiplatform
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Cache Kotlin packages
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}

      - name: Set Version to Tag Name
        id: tag_name
        if: github.event_name == 'release'
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Test
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION || 'development' }}
        run: ./gradlew test publishToMavenLocal

      - name: Test integration w/ minimum required versions
        if: github.event_name != 'release'
        run: ./gradlew test -p integration-tests

      - name: Configure AWS Credentials
        if: github.repository == 'adsbynimbus/nimbus-openrtb' && github.event_name == 'release'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: us-east-1

      - name: Publish
        if: github.repository == 'adsbynimbus/nimbus-openrtb' && github.event_name == 'release'
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
        run: ./gradlew publish
