name: Kotlin

on:
  pull_request:
    paths:
      - 'kotlin/**'
      - '.github/workflows/kotlin*'

  push:
    branches:
      - main
    paths:
      - 'kotlin/**'
      - '.github/workflows/kotlin*'

  release:
    types: [published]

jobs:

  build:
    name: Build Kotlin Multiplatform
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Kotlin packages
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}
            ${{ runner.os }}-konan-

      - name: Set Version from Tag Name
        id: tag_name
        if: github.event_name == 'release'
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

      - name: Test
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION || '0.0.1' }}
        run: ./gradlew test publishToMavenLocal

      - name: Publish
        if: github.repository == 'timehop/nimbus-openrtb' && github.event_name == 'release'
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
          ORG_GRADLE_PROJECT_awsAccessKey: ${{ secrets.NIMBUS_MOBILE_AWS_ACCESS_KEY }}
          ORG_GRADLE_PROJECT_awsSecretKey: ${{ secrets.NIMBUS_MOBILE_AWS_SECRET_KEY }}
        run: ./gradlew publish
