name: Kotlin

on:
  pull_request:
    paths:
      - '.github/workflows/kotlin*'
      - 'gradle/**'
      - 'kotlin/**'

  push:
    branches:
      - main
    paths:
      - '.github/workflows/kotlin*'
      - 'gradle/**'
      - 'kotlin/**'

  release:
    types: [published]

jobs:

  build:
    name: Build Kotlin Multiplatform
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Kotlin packages
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('**/*.versions.toml') }}
            ${{ runner.os }}-konan-

      - name: Set Version to Tag Name
        id: tag_name
        if: github.event_name == 'release'
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Test
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION || '0.0.1' }}
        run: ./gradlew test publishToMavenLocal

      - name: Configure AWS Credentials
        if: github.repository == 'timehop/nimbus-openrtb' && github.event_name == 'release'
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: us-east-1

      - name: Publish
        if: github.repository == 'timehop/nimbus-openrtb' && github.event_name == 'release'
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.tag_name.outputs.VERSION }}
        run: ./gradlew publish
